declare module 'react-native-ico-sensa-emoji-vectors' {
    import { ReactNode } from 'react';
    import { SvgProps, AdditionalProps } from 'react-native-svg';

    type iconNames = 'airplane' |
      'angry-face' |
      'anguished-face' |
      'anxious-face-with-sweat' |
      'astonished-face' |
      'avocado' |
      'backhand-index-pointing-down-skin-1' |
      'backhand-index-pointing-down-skin-2' |
      'backhand-index-pointing-down-skin-3' |
      'backhand-index-pointing-down-skin-4' |
      'backhand-index-pointing-down-skin-5' |
      'backhand-index-pointing-down' |
      'backhand-index-pointing-left-skin-1' |
      'backhand-index-pointing-left-skin-2' |
      'backhand-index-pointing-left-skin-3' |
      'backhand-index-pointing-left-skin-4' |
      'backhand-index-pointing-left-skin-5' |
      'backhand-index-pointing-left' |
      'backhand-index-pointing-right-skin-1' |
      'backhand-index-pointing-right-skin-2' |
      'backhand-index-pointing-right-skin-3' |
      'backhand-index-pointing-right-skin-4' |
      'backhand-index-pointing-right-skin-5' |
      'backhand-index-pointing-right' |
      'backhand-index-pointing-up-skin-1' |
      'backhand-index-pointing-up-skin-2' |
      'backhand-index-pointing-up-skin-3' |
      'backhand-index-pointing-up-skin-4' |
      'backhand-index-pointing-up-skin-5' |
      'backhand-index-pointing-up' |
      'baltasar' |
      'banana' |
      'beach-with-umbrella' |
      'beach' |
      'beaming-face-with-smiling-eyes' |
      'bell' |
      'bicycle' |
      'broken-heart' |
      'bubbles' |
      'calendar' |
      'call-me-hand-skin-1' |
      'call-me-hand-skin-2' |
      'call-me-hand-skin-4' |
      'call-me-hand-skin-5' |
      'call-me-hand' |
      'camera' |
      'cat' |
      'check-mark' |
      'clapping-hands-skin-1' |
      'clapping-hands-skin-2' |
      'clapping-hands-skin-3' |
      'clapping-hands-skin-4' |
      'clapping-hands-skin-5' |
      'clapping-hands' |
      'clock' |
      'clown-face' |
      'cold-face' |
      'compass' |
      'confounded-face' |
      'cool' |
      'cowboy-hat-face' |
      'crossed-fingers-skin-1' |
      'crossed-fingers-skin-2' |
      'crossed-fingers-skin-3' |
      'crossed-fingers-skin-4' |
      'crossed-fingers-skin-5' |
      'crossed-fingers' |
      'crying-face' |
      'crystal-ball' |
      'dissapointed-face' |
      'dizzy-face' |
      'dog' |
      'downcast-face-with-sweat' |
      'drooling-face' |
      'eggplant' |
      'envelope' |
      'exploding-head' |
      'expressioless-face' |
      'face-blowing-a-kiss' |
      'face-savoring-food' |
      'face-screaming-in-fear' |
      'face-with-hand-over-mouth' |
      'face-with-head-bandage' |
      'face-with-medical-mask' |
      'face-with-monocle' |
      'face-with-open-mouth' |
      'face-with-raised-eyebrow' |
      'face-with-rolling-eyes' |
      'face-with-steam-from-nose' |
      'face-with-symbols-on-mouth' |
      'face-with-tears-of-joy' |
      'face-with-thermometer' |
      'face-with-tongue' |
      'face-without-mouth' |
      'fearful-face' |
      'fire' |
      'flushed-face' |
      'folded-hands-skin-1' |
      'folded-hands-skin-2' |
      'folded-hands-skin-3' |
      'folded-hands-skin-4' |
      'folded-hands-skin-5' |
      'folded-hands' |
      'free' |
      'frowning-face-with-open-mouth' |
      'frowning-face' |
      'gaspar' |
      'gemstone' |
      'glasses' |
      'green-apple' |
      'grimacing-face' |
      'grinning-face-1' |
      'grinning-face-with-big-eyes' |
      'grinning-face-with-sweat' |
      'grinning-face' |
      'grinning-squinting-face' |
      'group' |
      'hamburger' |
      'hand-with-fingers-splayed-skin-1' |
      'hand-with-fingers-splayed-skin-2' |
      'hand-with-fingers-splayed-skin-3' |
      'hand-with-fingers-splayed-skin-4' |
      'hand-with-fingers-splayed-skin-5' |
      'hand-with-fingers-splayed' |
      'handshake-skin-1' |
      'handshake-skin-2' |
      'handshake-skin-3' |
      'handshake-skin-4' |
      'handshake-skin-5' |
      'handshake' |
      'heart' |
      'high-voltage' |
      'hot-face' |
      'house' |
      'hugging-face' |
      'hushed-face' |
      'index-pointing-up-skin-1' |
      'index-pointing-up-skin-2' |
      'index-pointing-up-skin-3' |
      'index-pointing-up-skin-4' |
      'index-pointing-up-skin-5' |
      'index-pointing-up' |
      'joker' |
      'kissing-face-with-closed-eyes' |
      'kissing-face-with-smiling-eyes' |
      'kissing-face' |
      'kiwi' |
      'landmark' |
      'left-facing-fist-skin-1' |
      'left-facing-fist-skin-2' |
      'left-facing-fist-skin-3' |
      'left-facing-fist-skin-4' |
      'left-facing-fist-skin-5' |
      'left-facing-fist' |
      'lion' |
      'loudly-crying-face' |
      'love-you-gesture-skin-1' |
      'love-you-gesture-skin-2' |
      'love-you-gesture-skin-3' |
      'love-you-gesture-skin-4' |
      'love-you-gesture-skin-5' |
      'love-you-gesture' |
      'lying-face' |
      'mailbox' |
      'melchor' |
      'middle-finger-skin-1' |
      'middle-finger-skin-2' |
      'middle-finger-skin-3' |
      'middle-finger-skin-4' |
      'middle-finger-skin-5' |
      'middle-finger' |
      'money-mouth-face-1' |
      'money-mouth-face-2' |
      'money-mouth-face-3' |
      'money-mouth-face-bitcoin' |
      'money-mouth-face' |
      'monkey' |
      'nauseated-face' |
      'nerd-face' |
      'neutral-face' |
      'ok-hand-skin-1' |
      'ok-hand-skin-2' |
      'ok-hand-skin-3' |
      'ok-hand-skin-4' |
      'ok-hand-skin-5' |
      'ok-hand' |
      'ok' |
      'oncoming-fist-skin-1' |
      'oncoming-fist-skin-2' |
      'oncoming-fist-skin-3' |
      'oncoming-fist-skin-4' |
      'oncoming-fist-skin-5' |
      'oncoming-fist' |
      'open-hands-skin-1' |
      'open-hands-skin-2' |
      'open-hands-skin-3' |
      'open-hands-skin-4' |
      'open-hands-skin-5' |
      'open-hands' |
      'palm' |
      'palms-up-together-skin-1' |
      'palms-up-together-skin-2' |
      'palms-up-together-skin-3' |
      'palms-up-together-skin-4' |
      'palms-up-together-skin-5' |
      'palms-up-together' |
      'panda' |
      'party-popper' |
      'partying-face' |
      'peach' |
      'pencil' |
      'pensive-face' |
      'pile-of-poo' |
      'pinch-hand-skin-1' |
      'pinch-hand-skin-2' |
      'pinch-hand-skin-3' |
      'pinch-hand-skin-4' |
      'pinch-hand-skin-5' |
      'pinch-hand' |
      'pinched-fingers-skin-1' |
      'pinched-fingers-skin-2' |
      'pinched-fingers-skin-3' |
      'pinched-fingers-skin-4' |
      'pinched-fingers-skin-5' |
      'pinched-fingers' |
      'pizza' |
      'pleading-face' |
      'pouting-face' |
      'rainbow' |
      'raised-back-of-hand-skin-1' |
      'raised-back-of-hand-skin-2' |
      'raised-back-of-hand-skin-3' |
      'raised-back-of-hand-skin-4' |
      'raised-back-of-hand-skin-5' |
      'raised-back-of-hand' |
      'raised-fist-skin-1' |
      'raised-fist-skin-2' |
      'raised-fist-skin-3' |
      'raised-fist-skin-4' |
      'raised-fist-skin-5' |
      'raised-fist' |
      'raised-hand-skin-1' |
      'raised-hand-skin-2' |
      'raised-hand-skin-3' |
      'raised-hand-skin-4' |
      'raised-hand-skin-5' |
      'raised-hand' |
      'raising-hands-skin-1' |
      'raising-hands-skin-2' |
      'raising-hands-skin-3' |
      'raising-hands-skin-4' |
      'raising-hands-skin-5' |
      'raising-hands' |
      'recycling-symbol' |
      'red-apple' |
      'relieved-face' |
      'right-facing-fist-skin-1' |
      'right-facing-fist-skin-2' |
      'right-facing-fist-skin-3' |
      'right-facing-fist-skin-4' |
      'right-facing-fist-skin-5' |
      'right-facing-fist' |
      'robot' |
      'rocket' |
      'rolling-on-the-floor-laughing' |
      'round-pushpin' |
      'sad-but-relieved-face' |
      'santa-claus' |
      'scrunched-face' |
      'shushing-face' |
      'sign-of-the-horns-skin-1' |
      'sign-of-the-horns-skin-2' |
      'sign-of-the-horns-skin-3' |
      'sign-of-the-horns-skin-4' |
      'sign-of-the-horns-skin-5' |
      'sign-of-the-horns' |
      'sleep-face' |
      'sleepy-face' |
      'slightly-frowning-face' |
      'slightly-smiling-face' |
      'smiling-face-with-halo' |
      'smiling-face-with-heart-eyes' |
      'smiling-face-with-hearts' |
      'smiling-face-with-smiling-eyes' |
      'smiling-face-with-sunglasses' |
      'smiling-face' |
      'smirking-face' |
      'sneezing-face' |
      'sparkles' |
      'squinting-face-with-tongue' |
      'star-struck' |
      'star' |
      'sweat-droplets' |
      'thinking-face' |
      'thumbs-down-skin-1' |
      'thumbs-down-skin-2' |
      'thumbs-down-skin-3' |
      'thumbs-down-skin-4' |
      'thumbs-down-skin-5' |
      'thumbs-down' |
      'thumbs-up-skin-1' |
      'thumbs-up-skin-2' |
      'thumbs-up-skin-3' |
      'thumbs-up-skin-4' |
      'thumbs-up-skin-5' |
      'thumbs-up' |
      'tired-face' |
      'umbrella-with-rain-drops' |
      'unamused-face' |
      'unicorn' |
      'upside-down-face' |
      'victory-hand-skin-1' |
      'victory-hand-skin-2' |
      'victory-hand-skin-3' |
      'victory-hand-skin-4' |
      'victory-hand-skin-5' |
      'victory-hand' |
      'vomiting-face' |
      'vulcan-salute-skin-1' |
      'vulcan-salute-skin-2' |
      'vulcan-salute-skin-3' |
      'vulcan-salute-skin-4' |
      'vulcan-salute-skin-5' |
      'vulcan-salute' |
      'waving-hand-skin-1' |
      'waving-hand-skin-2' |
      'waving-hand-skin-3' |
      'waving-hand-skin-4' |
      'waving-hand-skin-5' |
      'waving-hand' |
      'weary-face' |
      'weather' |
      'winking-face-with-tongue' |
      'winking-face' |
      'woozy-face' |
      'worried-face-1' |
      'worried-face' |
      'writing-hand-skin-1' |
      'writing-hand-skin-2' |
      'writing-hand-skin-3' |
      'writing-hand-skin-4' |
      'writing-hand-skin-5' |
      'writing-hand' |
      'xmas-ball' |
      'xmas-tree' |
      'yawning-face' |
      'zany-face' |
      'zipper-mouth-face';

    type backgroundType = 'circle' | 'rect' | 'button';

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
